// PHASE 2 — Monthly PDF Performance Report Generator
// Aggregates all metrics for a client and delivers report via WhatsApp

const { sendDocument } = require('../utils/whatsapp');
const { formatRM } = require('../utils/currency');
const db = require('../db/client');

// Aggregate all metrics for the given month
async function gatherMetrics(clientId, year, month) {
  const start = new Date(year, month - 1, 1).toISOString();
  const end = new Date(year, month, 1).toISOString();

  const [ordersRes, reviewsRes, postsRes, broadcastsRes] = await Promise.all([
    db.from('orders').select('total_rm, status').eq('client_id', clientId).gte('created_at', start).lt('created_at', end),
    db.from('google_reviews').select('star_rating, response_posted').eq('client_id', clientId).gte('created_at', start).lt('created_at', end),
    db.from('content_calendar').select('status').eq('client_id', clientId).gte('created_at', start).lt('created_at', end),
    db.from('broadcasts').select('recipient_count').eq('client_id', clientId).gte('created_at', start).lt('created_at', end),
  ]);

  const orders = ordersRes.data || [];
  const reviews = reviewsRes.data || [];
  const posts = postsRes.data || [];
  const broadcasts = broadcastsRes.data || [];

  const totalRevenue = orders.filter(o => o.status !== 'cancelled').reduce((sum, o) => sum + (o.total_rm || 0), 0);
  const avgRating = reviews.length
    ? (reviews.reduce((s, r) => s + r.star_rating, 0) / reviews.length).toFixed(1)
    : 'N/A';

  return {
    orders: { count: orders.length, revenue: totalRevenue },
    reviews: { count: reviews.length, responded: reviews.filter(r => r.response_posted).length, avgRating },
    posts: { published: posts.filter(p => p.status === 'published').length, total: posts.length },
    broadcasts: { sent: broadcasts.length, recipients: broadcasts.reduce((s, b) => s + (b.recipient_count || 0), 0) },
  };
}

// Generate a plain-text report (PDF generation with Puppeteer is Phase 2 infra)
async function generateAndSendReport(client, year, month) {
  const metrics = await gatherMetrics(client.id, year, month);
  const monthName = new Date(year, month - 1).toLocaleString('en-MY', { month: 'long' });

  const report = [
    `📊 *Monthly Report — ${monthName} ${year}*`,
    `*${client.business_name}*`,
    `─────────────────────────`,
    `🛍️ Orders: ${metrics.orders.count}`,
    `💰 Revenue: ${formatRM(metrics.orders.revenue)}`,
    `─────────────────────────`,
    `⭐ Google Reviews: ${metrics.reviews.count}`,
    `   Avg rating: ${metrics.reviews.avgRating}`,
    `   Responded: ${metrics.reviews.responded}/${metrics.reviews.count}`,
    `─────────────────────────`,
    `📱 Social posts: ${metrics.posts.published}/${metrics.posts.total} published`,
    `📢 Broadcasts: ${metrics.broadcasts.sent} sent → ${metrics.broadcasts.recipients} recipients`,
    `─────────────────────────`,
    `Report generated by Naik Agency 🚀`,
  ].join('\n');

  // Send as WhatsApp text for now; swap for sendDocument(PDF) in Phase 2
  const { sendMessage } = require('../utils/whatsapp');
  await sendMessage(client.whatsapp_number, report);

  console.log(`📊 Report sent to ${client.business_name} for ${monthName} ${year}`);
}

module.exports = { generateAndSendReport };
// ✅ src/reports/monthly.js complete
