export function monthlyReportPrompt(params: {
  reportMonth: string
  metrics: {
    instagram_reach?: number
    instagram_followers_start?: number
    instagram_followers_end?: number
    instagram_saves?: number
    tiktok_views?: number
    google_review_score?: number
    google_review_count?: number
    new_customer_estimate?: number
    revenue_this_month?: number
    revenue_last_month?: number
    top_performing_post?: string
    notes_from_operator?: string
  }
}): string {
  return `Generate a monthly CMO report for ${params.reportMonth}.

PERFORMANCE DATA:
${JSON.stringify(params.metrics, null, 2)}

Output a professional client-ready report in markdown:

## ${params.reportMonth} Marketing Performance Report

### Executive Summary
(2-3 sentences: what happened this month in plain language)

### Key Wins
(Bullet list — specific, data-backed achievements)

### What the Numbers Tell Us
(Interpret each metric with business context, not just raw numbers)

### Revenue Impact Assessment
${params.metrics.revenue_this_month && params.metrics.revenue_last_month
  ? `(Month-on-month comparison: RM ${params.metrics.revenue_last_month} → RM ${params.metrics.revenue_this_month}. What drove the change?)`
  : '(Commentary on business trajectory based on available data)'}

### What Didn't Work
(Honest assessment — what underperformed and why)

### Next Month Priorities
(Exactly 3 priorities — specific, actionable, measurable)

### Recommended Actions Before Next Month
(Checklist of 5 specific tasks)

---
*Report generated by Naik | ${new Date().toLocaleDateString('en-MY')}*

Write like a CMO presenting to a business owner — direct, honest, no marketing jargon.`
}
